name: joshua-portfolio
recipe: wordpress
proxy:
  appserver_nginx:
    - joshua-portfolio.lndo.site
services:
  database:
    portforward: 3306
  pma:
    type: phpmyadmin
    hosts:
      - database
config:
  webroot: web
  php: '8.1'
  via: nginx
  database: mysql
